version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3003:3003"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env  
    volumes:
      - .:/app
      - /app/node_modules
    # command: npm run dev